# Generated by Django 3.1.5 on 2021-01-26 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adviser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='回答者')),
            ],
            options={
                'verbose_name': 'adviser',
                'verbose_name_plural': '回答者',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clt_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='相談者')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': '相談者',
            },
        ),
        migrations.CreateModel(
            name='Relevant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adviser', models.ManyToManyField(related_name='adviser', to='relevant.Adviser')),
                ('client', models.ManyToManyField(related_name='client', to='relevant.Client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'relevant',
                'verbose_name_plural': 'コミニティ',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(verbose_name='相談内容')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relevant.client', verbose_name='相談者')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': '相談内容',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='回答内容')),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relevant.adviser', verbose_name='回答者')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': '回答内容',
            },
        ),
    ]
