# Generated by Django 3.1.5 on 2021-01-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relevant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relevant',
            name='adviser',
            field=models.ManyToManyField(blank=True, null=True, related_name='adviser', to='relevant.Adviser'),
        ),
        migrations.AlterField(
            model_name='relevant',
            name='client',
            field=models.ManyToManyField(blank=True, null=True, related_name='client', to='relevant.Client'),
        ),
    ]
