# Generated by Django 3.1.5 on 2021-01-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_delete_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
