# Generated by Django 3.1.5 on 2021-01-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='account name'),
        ),
    ]
